feat(post): up-6327 query postv4
AmityCo/apidocs pull request #37
Opened 2021-12-10 06:12 UTC by kazekunz

Add query post v4 document

2021-12-20 03:53 UTC, dreamxchange approved these changes

2022-01-28 05:06 UTC, dreamxchange requested changes

2022-01-28 05:06 UTC, dreamxchange commented on v4/post/socket.yaml
> +            dataType:
max length?

2022-01-28 05:24 UTC, kazekunz commented on v4/post/socket.yaml
> +            dataType:
dataType is removed krub. This field deprecated use dataTypes instead.

2022-01-31 10:00 UTC, merged