docs(notification): up-4432 add swagger doc for /v2/notification
AmityCo/apidocs pull request #5
Opened 2021-09-22 09:41 UTC by alimran

2021-09-22 11:13 UTC, dreamxchange requested changes

2021-09-22 11:13 UTC, dreamxchange commented on swagger.yaml
> +          application/json:
To improve doc, please add more validation such as max length or enum for provider.

2021-09-22 11:13 UTC, dreamxchange commented on swagger.yaml
> +      requestBody:
Why do we need this one?

2021-09-23 04:51 UTC, alimran commented on swagger.yaml
> +  /v2/notification:
changed to v3

2021-09-23 04:51 UTC, alimran commented on swagger.yaml
> +          application/json:
validation provided using enum

2021-09-23 04:52 UTC, alimran commented on swagger.yaml
> +      requestBody:
removed the unused segment "requestBody"

2021-09-23 06:02 UTC, dreamxchange approved these changes

2021-09-23 06:02 UTC, merged