feat(update video post): up-8000 Update attachments in video post
AmityCo/apidocs pull request #60
Opened 2022-03-24 09:25 UTC by Pachara0Pin

Update post
- add `attachments` to API PUT `api/v4/post`
- add `attachments` to RPC POST `sockets/v4/post.update`

2022-03-24 18:22 UTC, dreamxchange requested changes

2022-03-24 18:22 UTC, dreamxchange commented on v4/post/api.yaml
> +                    description: file id for attachments
attachments -> attachment

2022-03-24 18:22 UTC, dreamxchange commented on v4/post/socket.yaml
> +                    description: file id for attachments
attachments -> attachment

2022-03-25 06:49 UTC, xypherbo approved these changes

2022-03-25 12:28 UTC, merged